image: node:lts

stages:
  - build
  - deploy

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build
    - mv dist public
  artifacts:
    paths:
      - public  # Especificamos la carpeta que GitLab Pages debe usar para el despliegue

pages:
  stage: deploy
  script:
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - main  # Esto asegura que solo la rama principal (main) se desplegará en GitLab Pages
