image: node:lts

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/  # Cachear node_modules para acelerar futuras ejecuciones

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build
    - mv dist public  # Mueve la carpeta dist a public para GitLab Pages
  artifacts:
    paths:
      - public  # GitLab Pages necesita la carpeta public
  only:
    - main  # Solo se ejecutará en la rama main

pages:
  stage: deploy
  script:
    - echo "Despliegue completado"
  artifacts:
    paths:
      - public  # La carpeta que se usará para el hosting
  only:
    - main
